### ISSUE TITLE
Xcode Build Fail but no error output log

### ISSUE THREAD

**Issue by martin09112000** [bitrise-steplib/bitrise-step-flutter-build#47]
### Issue description
I faced with issue build fail in IOS. With same version, branch, commit, workflow that I built success in last week, but now it was fail. 
I tried build in local and it succeed. Please support?

`Xcode version 14.2.x`
### Bitrise info

- Build URL: https://app.bitrise.io/build/40e6b3e0-d53e-4f86-b963-e66a52b218e7
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES / NO_
- Log:

<details>
  <pre>
 Config:
- project_location: .
- platform: both
- additional_build_params: --build-number=94
- is_debug_mode: false
- cache_level: all
- ios_output_type: app
- ios_additional_params: --release --flavor staging -t lib/main.dart 
- ios_output_pattern: [*build/ios/iphoneos/*.app *build/ios/archive/*.xcarchive]
- ios_codesign_identity: <unset>
- android_output_type: apk
- android_additional_params: --release --flavor staging -t lib/main.dart 
- android_output_pattern: [*build/app/outputs/apk/*/*.apk *build/app/outputs/bundle/*/*.aab]
- android_bundle_output_pattern: [*build/app/outputs/bundle/*/*.aab]
iOS Codesign settings
 - Skipping codesign preparation because output type is iOS app, not xcarchive
Build iOS app
$ flutter "build" "ios" "--build-number=94" "--release" "--flavor" "staging" "-t" "lib/main.dart" "--no-codesign"
Downloading ios tools...                                        
 2,298ms
Downloading ios-profile tools...                                
 1,193ms
Downloading ios-release tools...                                
 1,639ms
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building sg.vinova.resource.staging for device (ios-release)...
Running pod install...                                          
   33.0s
Running Xcode build...                                          
Xcode build done.                                            7.8s
Failed to build iOS app
Uncategorized (Xcode): Exited with status code 1
Encountered error while building for device.
Run: failed to build iOS app: exit status 1
  </pre>
</details>

### Steps to reproduce

1. Run build 
2. Fail but no log error out put about Xcode

<img width="1206" alt="Screenshot 2023-07-06 at 09 57 31" src="https://github.com/bitrise-steplib/bitrise-step-flutter-build/assets/126542347/dfa812bc-5238-40cf-812f-43e6d570e7e6">

**Comment by martin09112000** [comment]
I tried `pod install / flutter clean / flutter pub get` but inefficient

**Comment by martin09112000** [comment]
My workflow (stuck at `Flutter build`):
<img width="389" alt="Screenshot 2023-07-06 at 09 59 40" src="https://github.com/bitrise-steplib/bitrise-step-flutter-build/assets/126542347/992d9407-b1b7-4db1-8e4c-cad0979696ae">

**Comment by karlasgeir** [comment]
I'm currently encountering an identical issue with my Flutter project on Bitrise. Initially, I thought the problem had surfaced when I added Live Activities to the Flutter app. I upgraded from a stack using an Xcode version of 14.1.x to 14.3.x and started seeing this issue. I switched to a stack with Xcode version 14.2 and managed to achieve a successful build. At that point, I was under the impression that the issue was isolated to the 14.3 stack.

However, subsequent builds using the 14.2 stack have now begun to fail with the same non-helpful error and I've even tried to switch back to the 14.1 stack and build from a branch that does not contain the Live Activities changes, and I'm getting the same error.

When I run the equivalent flutter build command locally, the build completes without any issues.

Furthermore, I've attempted to add a "flutter clean" command within a Script step prior to the main build step on Bitrise, but this has not resolved the issue.

**Comment by karlasgeir** [comment]
We figured out what the issue was in our case. It was due to Bitrise changing the Ruby versions to Ruby > 3.0.

One package that we are using doesn't support Ruby > 3.0 causing the build to fail. We were using Ruby 2.7.6 locally and therefore the build worked there.

To verify that it was the issue, I created a script step to change the Ruby version to 2.7.6 as described here: https://devcenter.bitrise.io/en/infrastructure/build-stacks/ruby-versions-on-bitrise.html

After making this adjustment, our Bitrise builds are now passing successfully, although we will need to change out this library to support Ruby > 3.0

**Comment by martin09112000** [comment]
> We figured out what the issue was in our case. It was due to Bitrise changing the Ruby versions to Ruby > 3.0.
> 
> One package that we are using doesn't support Ruby > 3.0 causing the build to fail. We were using Ruby 2.7.6 locally and therefore the build worked there.
> 
> To verify that it was the issue, I created a script step to change the Ruby version to 2.7.6 as described here: https://devcenter.bitrise.io/en/infrastructure/build-stacks/ruby-versions-on-bitrise.html
> 
> After making this adjustment, our Bitrise builds are now passing successfully, although we will need to change out this library to support Ruby > 3.0

Thanks for information. Your solution really **save my life**!
